### ISSUE TITLE
Метод, возвращающий все темплейты по группе

### ISSUE THREAD

**Issue by dowellkin** [ione-cloud/ione-sunstone#14]
Нужен метод, который бы возвращал что-то в роде результата следующего sql запроса
```sql
SELECT * FROM `templates` WHERE `group` = '$peremenaya'
```

**Comment by slntopp** [comment]
Added with https://github.com/ione-cloud/ione-sunstone/commit/6b90d48aa7483e561087c6d86d238497f8ba6a6b
