### ISSUE TITLE
Ошибка при создании токена

### ISSUE THREAD

**Issue by dowellkin** [ione-cloud/ione-sunstone#17]
Ошибка при создании токена от админа юзеру используя api login (one.u.login)

**Comment by slntopp** [comment]
Пример ошибки

**Comment by dowellkin** [comment]
вот пример ошибки:
![image](https://user-images.githubusercontent.com/18235187/94813889-3ffdad00-0401-11eb-833c-f0b36be6d54a.png)

**Comment by dowellkin** [comment]
Вот пример
![image](https://user-images.githubusercontent.com/18235187/94814026-720f0f00-0401-11eb-9c10-dbe91e7f9b66.png)

**Comment by slntopp** [comment]
А запрос?)

**Comment by slntopp** [comment]
https://forum.opennebula.io/t/error-when-generating-login-token/6146/3?u=slnt_opp
