### ISSUE TITLE
Ошибка при реинстале тачки

### ISSUE THREAD

**Issue by dowellkin** [ione-cloud/ione-sunstone#18]
После запроса на реинстал тачки, старая удаляется, но новая не появляется

**Comment by slntopp** [comment]
Артефакт старых версий - будет пофикшено в следующей версии. Сейчас просто добавь release -> true в параметры
https://github.com/ione-cloud/ione-sunstone/blob/26324226c721019d336cc585bad258511fb0dd33/ione/server/lib/creative_funcs/main.rb#L141-L142
