### ISSUE TITLE
Ошибки возвращаются в виде веб страницы

### ISSUE THREAD

**Issue by dowellkin** [ione-cloud/ione-sunstone#19]
вместо обычного json типа 
```json
{"result": "error", "message": "ошибка"}
```
возвращается целая веб страница

**Comment by slntopp** [comment]
Пример запроса?

**Comment by dowellkin** [comment]
http://domain:8009/one.u.login

`{"auth":"login:password","oid":1834,"args":["user_11638","",3600]}`

**Comment by slntopp** [comment]
Ничего не поделать)
