### ISSUE TITLE
get_user_vnets и one.u.billable_vns возвращают "#"

### ISSUE THREAD

**Issue by dowellkin** [ione-cloud/ione-sunstone#21]
методы:
https://domain/ione/get_user_vnets
`{"params":[1847]}`;

http://domain:8009/one.u.billable_vns
`{"auth":"login:pass","oid":1847}`

возвращают массив с элементами вида "#". Их количество совпадает с количеством зарезервированных ip, но нет возможности получить айди для подстановки в запрос.

**Comment by slntopp** [comment]
Resolved in #20
