### ISSUE TITLE
install.rb missing / update readme file

### ISSUE THREAD

**Issue by darkfritz2** [ione-cloud/ione-sunstone#8]
install.rb from the readme file is missing. can't install it.

or update the readme file to install it?

**Comment by slntopp** [comment]
Hi, thanks for noticing.
Now you should use `rake install` instead of install.rb
We'll update readme asap

**Comment by slntopp** [comment]
Also, it would be very cool, if you could tell us how did it go after, installation process needs a lot of improvements 😅

**Comment by darkfritz2** [comment]
ok. done it. got the error:

Nothing to do
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as
root will break this application for all non-root users on this machine.
Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a
line like this to your Gemfile:
source 'https://rubygems.org'
Could not find gem 'nori (= 2.6.0)' in any of the gem sources listed in your Gemfile.
Error installing gems
rake aborted!
Command failed with status (255): [/usr/share/one/install_gems --yes...]
rake/install_gems.rake:25:in `block in <top (required)>'
Tasks: TOP => install => install_gems
(See full trace by running task with --trace)

**Comment by slntopp** [comment]
Try to run `/usr/lib/one/sunstone/install_gems` or install gems from `/usr/lib/one/sunstone/Gemfile` by yourself.
Also, check which ruby and gem version you have.

**Comment by slntopp** [comment]
Basically you should make `install_gems` working or all the gems installed, then you can just proceed with rest `rake` tasks with:
```
rake install_ione
rake install_ui
```

**Comment by darkfritz2** [comment]
okay. so after investigating:
ruby -v showed me that i had 2.0.0 installed
to use /usr/share/one/install_gems i had to install ruby 2.3.0 or greater. so i installed ruby 2.7.0 using these commands:

cd
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec $SHELL

git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
exec $SHELL

rbenv install 2.7.0

rbenv global 2.7.0

after this i had the sequel gem because it's there are 2 different version (apparently i had 2.25 and now i installed 2.17....)

after i used rake install_ione it installed all the packages but now i can't start the opennebula.service

opennebula.service - OpenNebula Cloud Controller Daemon
   Loaded: loaded (/usr/lib/systemd/system/opennebula.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sat 2020-05-30 10:51:40 EEST; 4min 20s ago
  Process: 29535 ExecStopPost=/usr/share/one/follower_cleanup (code=exited, status=0/SUCCESS)
  Process: 29533 ExecStart=/usr/bin/oned -f (code=exited, status=255)
  Process: 29530 ExecStartPre=/usr/sbin/logrotate -f /etc/logrotate.d/opennebula -s /var/lib/one/.logrotate.status (code=exited, status=1/FAILURE)
 Main PID: 29533 (code=exited, status=255)

May 30 10:51:35 BC2-BL8 systemd[1]: Failed to start OpenNebula Cloud Controller Daemon.
May 30 10:51:35 BC2-BL8 systemd[1]: Unit opennebula.service entered failed state.
May 30 10:51:35 BC2-BL8 systemd[1]: opennebula.service failed.
May 30 10:51:40 BC2-BL8 systemd[1]: opennebula.service holdoff time over, scheduling restart.
May 30 10:51:40 BC2-BL8 systemd[1]: Stopped OpenNebula Cloud Controller Daemon.
May 30 10:51:40 BC2-BL8 systemd[1]: start request repeated too quickly for opennebula.service
May 30 10:51:40 BC2-BL8 systemd[1]: Failed to start OpenNebula Cloud Controller Daemon.
May 30 10:51:40 BC2-BL8 systemd[1]: Unit opennebula.service entered failed state.
May 30 10:51:40 BC2-BL8 systemd[1]: opennebula.service failed.

**Comment by slntopp** [comment]
You should never try to update ruby, OpenNebula works **only** with ruby 2.0.0

**Comment by darkfritz2** [comment]
otherwise it doesn't work for me. bundle install or any other command it wants ruby 2.3.0 or greater.

i will install in the next few days on a virtual machine and do some testing.
